// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_XOAnq56a4dSYZfLWZo3mODgOsmr-JY',
    appId: '1:634361672473:web:4b511ba4a8e7c8df104b88',
    messagingSenderId: '634361672473',
    projectId: 'cilthastaliklari-2ef11',
    authDomain: 'cilthastaliklari-2ef11.firebaseapp.com',
    storageBucket: 'cilthastaliklari-2ef11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArhVmiqCF9BoNVWIK0uUYPXAdemKFSsys',
    appId: '1:634361672473:android:3a1b750ed5a045e6104b88',
    messagingSenderId: '634361672473',
    projectId: 'cilthastaliklari-2ef11',
    storageBucket: 'cilthastaliklari-2ef11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJPbqKH5tgRyqH1R-F-ZrVCt6u4CFp22Q',
    appId: '1:634361672473:ios:f44c64946fce6d7d104b88',
    messagingSenderId: '634361672473',
    projectId: 'cilthastaliklari-2ef11',
    storageBucket: 'cilthastaliklari-2ef11.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJPbqKH5tgRyqH1R-F-ZrVCt6u4CFp22Q',
    appId: '1:634361672473:ios:f44c64946fce6d7d104b88',
    messagingSenderId: '634361672473',
    projectId: 'cilthastaliklari-2ef11',
    storageBucket: 'cilthastaliklari-2ef11.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0_XOAnq56a4dSYZfLWZo3mODgOsmr-JY',
    appId: '1:634361672473:web:61bdc7a496a044b5104b88',
    messagingSenderId: '634361672473',
    projectId: 'cilthastaliklari-2ef11',
    authDomain: 'cilthastaliklari-2ef11.firebaseapp.com',
    storageBucket: 'cilthastaliklari-2ef11.firebasestorage.app',
  );
}
